using System;
using NXOpen;
using NXOpen.UF;
using NXOpenUI;
using NXOpen.Utilities;

public class Program
{

     static Session theSession = Session.GetSession();
    static UFSession theUFSession = UFSession.GetUFSession();
    
    public static Program theProgram;
    public static bool isDisposeCalled;

    static void CycleObjects()
    {
        Part parts = theSession.Parts.Work;
        Tag objTag = Tag.Null;
        ListingWindow listingWindow = theSession.ListingWindow;
        listingWindow.Open();
        string names = "";

        do
        {

            objTag = theUFSession.Obj.CycleAll(parts.Tag, objTag);

            if (objTag != Tag.Null)
            {
                TaggedObject taggedobj = NXObjectManager.Get(objTag);
                names = names + taggedobj.ToString() + "\n";
            }
        }
        while (objTag != Tag.Null);

        listingWindow.WriteLine(names);
    }



    public static void Main(string[] args)
    {
        try
        {

            CycleObjects();
          
        }
        catch (NXOpen.NXException ex)
        {

        }
    }

    public static int GetUnloadOption(string arg)
    {
      
         return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);

    }

}

